[package]
name = "darkdev"
version = "0.1.0"
edition = "2021"
description = "A development tool for watching and managing multiple projects"
authors = ["Shane Shown"]

[[bin]]
name = "ddw"
path = "src/bin/ddw.rs"

[[bin]]
name = "ddc"
path = "src/bin/ddc.rs"

[dependencies]
notify = "8.0"
notify-debouncer-full = "0.5"
tokio = { version = "1.39", features = ["full"] }
toml = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
pretty_env_logger = "0.5.0"
log = "0.4"
reqwest = { version = "0.12", features = ["json"] }
clap = { version = "4.4", features = ["derive"] }