[package]
name = "darkdev"
version = "0.1.0"
edition = "2021"

[dependencies]
notify = "6.1.1"
tokio = { version = "1.39.3", features = ["full"] }
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"