# Global settings for the build system
[global]
# Specify the default channel capacity
channel_capacity = 100
# Specify the default mode for all projects (can be overridden per project)
default_mode = "compile"
# Specify the default debounce delay in milliseconds
debounce_delay = 1000
# Specify the default logging level for all projects (can be overridden per project)
logging_level = "info"
# Global paths to watch for changes (can be inherited or overridden)
watch_paths = ["src/main/java", "src/test/java", "pom.xml"] # Inherits and overrides global paths
# Global file extensions to monitor (can be inherited or overridden)
watch_extensions = ["java", "kt", "kts", "xml"]

# Define all projects with their specific settings
[projects]

# Project A configuration
[projects.project_a]
# Path to the project directory
project_dir = "project-a"
# Override or add paths to watch for changes
# Inherit global file extensions (no need to redefine)
# List of dependent projects that should be built first
dependencies = ["project_b"]
# Override the default mode if needed
mode = "run"

# Commands specific to each mode for Project A
[projects.project_a.commands]
compile = { program = "mvn", args = ["-q", "compile"] }
test = { program = "mvn", args = ["-q", "test"] }
run = { program = "mvn", args = ["-q", "compile", "exec:java", "-Dexec.mainClass=dev.surly.a.HelloWorld"] }

# Project B configuration
[projects.project_b]
project_dir = "project-b"
# Inherit global watch paths and extensions
dependencies = []
mode = "install"

# Commands specific to each mode for Project B
[projects.project_b.commands]
compile = { program = "mvn", args = ["-q", "compile"] }
test = { program = "mvn", args = ["-q", "test"] }
install = { program = "mvn", args = ["-q", "install"] }

# kotlin-minimal-example
[projects.kotlin_minimal_example]
project_dir = "/home/shane/projects/kotlin-minimal-example"
watch_paths = ["src/main/kotlin", "build.gradle.kts"]
dependencies = []
mode = "jar_run"

[projects.kotlin_minimal_example.commands]
compile = { program = "./gradlew", args = ["clean", "build"] }
test = { program = "./gradlew", args = ["test"] }
jar = { program = "./gradlew", args = ["jar"] }
jar_run = { program = "java", args = ["-jar", "build/libs/kotlin-minimal-example-1.0-SNAPSHOT-standalone.jar"] }
